### ISSUE TITLE
Does this loop forever? :)

### ISSUE THREAD

**Issue by adamchester** [nblumhardt/serilog-blazor#1]
https://github.com/nblumhardt/serilog-blazor/blob/e0f1ba4f8015571570d9a94eee95d10444c61c03/SerilogBlazorDemo.Server/Diagnostics/SerilogClientLoggingMiddleware.cs#L55

**Comment by nblumhardt** [comment]
Would appear that it did! :-) ... Just YOLO-committed a fix, thanks.
