### ISSUE TITLE
Support custom HttpClient

### ISSUE THREAD

**Issue by benjaminsampica** [nblumhardt/serilog-blazor#19]
It would be nice to support a custom HttpClient that is already pre-configured such as in cases where authentication/authorization is being managed by a hosted ASP.NET Core API. Currently, only a custom messageHandler is supported and I see an HttpClient is being instantiated inside of the sink itself.

**Comment by GerkinDev** [comment]
+1 for this one. ~~This would allow dynamic AccessToken injection (in case it was refreshed) without over-complicating the sink.~~ A custom message handler can do most request pre-processing

**Comment by nblumhardt** [comment]
@benjaminsampica is there any option to do what you need via the message handler? There isn't a whole lot that `HttpClient` does that the message handler can't influence, so it'd be nice to avoid more API surface area if we can.

**Comment by benjaminsampica** [comment]
@nblumhardt Honestly, I’m not sure why I originally thought I needed this after looping back around to the problem I was trying to solve late at night. I ended up using the message handler which worked great and was the same amount of code the HttpClient solution would’ve been for me anyway. 

Feel free to close both issue and PR if there’s no perceivable value to you. Apologies!

**Comment by nblumhardt** [comment]
That's great - thanks Ben!

**Comment by mtavares628** [comment]
@benjaminsampica - Can you share an example of how you got the message handler working?  I'm trying to get this to work with authentication/authorization and it's not working.  I have tried the following, and can't get it to work:
```c#
var loggerHandler = builder.Services.BuildServiceProvider().GetRequiredService<AuthorizationMessageHandler>()
                    .ConfigureHandler(
                            authorizedUrls: new[] { builder.Configuration.GetValue<string>("ApiBaseUrl") },
                            scopes: new[] { "dadapi" });

var levelSwitch = new LoggingLevelSwitch();
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Enrich.WithProperty("InstanceId", Guid.NewGuid().ToString("n"))
    .WriteTo.BrowserHttp(endpointUrl: $"{builder.Configuration.GetValue<string>("ApiBaseUrl")}/ingest"
                        , controlLevelSwitch: levelSwitch
                        , messageHandler: loggerHandler)
    .WriteTo.BrowserConsole()
    .CreateLogger();
```

**Comment by benjaminsampica** [comment]
@mtavares628 heres my production code - hope it’s helpful!

https://github.com/benjaminsampica/DynamoLeagueBlazor/blob/7d340159f80e693ce81e3c9f955fe0e266e8a622/DynamoLeagueBlazor/Client/Program.cs#L21

https://github.com/benjaminsampica/DynamoLeagueBlazor/blob/7d340159f80e693ce81e3c9f955fe0e266e8a622/DynamoLeagueBlazor/Client/Program.cs#L45

**Comment by mtavares628** [comment]
Thanks @benjaminsampica, the code was helpful.  However, I'm still running into an issue with the httpclient.  My code is very similar to yours other than that I'm using an AuthorizationMessageHandler instead of BaseAddressAuthorizationMessageHandler because my application is talking to a Web API with a different base address.

@nblumhardt is it possible to reopen this issue?  Here's what I've found on my end.  When trying to step through the code, it appears that the httpclient becomes deadlocked on the PostAsync call whenever I pass in my AuthorizationMessageHandler.  So here's what my Program.cs looks like:
```c#

builder.Services.AddHttpClient("DadApi", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler(sp =>
                {
                    var handler = sp.GetRequiredService<AuthorizationMessageHandler>()
                        .ConfigureHandler(
                            authorizedUrls: new[] { builder.Configuration.GetValue<string>("ApiBaseUrl") },
                            scopes: new[] { "dadapi" });

                    return handler;
                });

builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("oidc", options.ProviderOptions);
    options.UserOptions.RoleClaim = "role";
    options.ProviderOptions.AdditionalProviderParameters.Add("ClientBaseUrl", builder.Configuration.GetValue<string>("BaseUrl"));
})
           
builder.Services.AddAuthorizationCore();
builder.Services.AddOptions();

builder.Logging.ClearProviders();
builder.Logging.AddSerilog();

var host = builder.Build();

var loggerHandler = host.Services.GetRequiredService<AuthorizationMessageHandler>();
                    .ConfigureHandler(
                            authorizedUrls: new[] { builder.Configuration.GetValue<string>("ApiBaseUrl") },
                            scopes: new[] { "dadapi" }
                            );

var levelSwitch = new LoggingLevelSwitch();

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Enrich.WithProperty("InstanceId", Guid.NewGuid().ToString("n"))
    .WriteTo.BrowserHttp(endpointUrl: $"{builder.Configuration.GetValue<string>("ApiBaseUrl")}/ingest"
                        , controlLevelSwitch: levelSwitch
                        , messageHandler: loggerHandler
                        )
    .WriteTo.BrowserConsole()
    .CreateLogger();

await host.RunAsync();
```
And in BrowserHttpSink class, it gets hung up on the PostAsync call in this method:

```c#
protected override async Task EmitBatchAsync(IEnumerable<LogEvent> events)
{
	_nextRequiredLevelCheckUtc = DateTime.UtcNow.Add(RequiredLevelCheckInterval);

	var payload = FormatCompactPayload(events, _eventBodyLimitBytes);

	var content = new StringContent(payload, Encoding.UTF8, SerilogServerApi.CompactLogEventFormatMimeType);

	var result = await _httpClient.PostAsync(_endpointUrl, content).ConfigureAwait(false);
	if (!result.IsSuccessStatusCode)
		throw new LoggingFailedException(
			$"Received failed result {result.StatusCode} when posting events to the server.");

	var returned = await result.Content.ReadAsStringAsync();
	_controlledSwitch.Update(SerilogServerApi.ReadEventInputResult(returned));
}
```
It just never comes back from the call, and is deadlocked.  Oddly enough, if I turn off requiring authorization on my API server, and do not pass in the MessageHandler the call goes through fine without an issue and ends up in the log on the server.

After doing some searching, I came across this [post](https://josef.codes/you-are-probably-still-using-httpclient-wrong-and-it-is-destabilizing-your-software/) regarding the use of HttpClient in .Net Core.

So I tried altering the BrowserHttpSink to allow me to pass in an HttpClient, and set the internal _httpClient to that value instead of creating a new one within the constructor.  I then altered my program.cs to create the HttpClient from IHttpClientFactory:

```c#
builder.Services.AddHttpClient("DadApi", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
                .AddHttpMessageHandler(sp =>
                {
                    var handler = sp.GetRequiredService<AuthorizationMessageHandler>()
                        .ConfigureHandler(
                            authorizedUrls: new[] { builder.Configuration.GetValue<string>("ApiBaseUrl") },
                            scopes: new[] { "dadapi" });

                    return handler;
                });

builder.Services.AddOidcAuthentication(options =>
{
    builder.Configuration.Bind("oidc", options.ProviderOptions);
    options.UserOptions.RoleClaim = "role";
    options.ProviderOptions.AdditionalProviderParameters.Add("ClientBaseUrl", builder.Configuration.GetValue<string>("BaseUrl"));
})

builder.Services.AddAuthorizationCore();
builder.Services.AddOptions();
builder.Logging.ClearProviders();
builder.Logging.AddSerilog();

var host = builder.Build();

var levelSwitch = new LoggingLevelSwitch();

var clientFactory = host.Services.GetRequiredService<IHttpClientFactory>();
var clt = clientFactory.CreateClient("DadApi");

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Enrich.WithProperty("InstanceId", Guid.NewGuid().ToString("n"))
    .WriteTo.BrowserHttp(endpointUrl: $"{builder.Configuration.GetValue<string>("ApiBaseUrl")}/ingest"
                        , controlLevelSwitch: levelSwitch
                        , httpClient: clt
                        )
    .WriteTo.BrowserConsole()
    .CreateLogger();

await host.RunAsync();
```
This worked!  So I'm not sure what the HttpClientFactory is doing differently to create the httpClient, but I didn't get any deadlock this way.

So all that being said, is it possible to revisit this, and possibly create an overload of the extension method to allow for passing in the HttpClient?

**Comment by nblumhardt** [comment]
Given the widespread use of `IHttpClientFactory` I think that makes sense, @mtavares628 👍 

I don't have any time to work on this, but would accept a PR if anyone's keen to implement.

**Comment by benjaminsampica** [comment]
@mtavares628 I originally took a crack at this in https://github.com/nblumhardt/serilog-sinks-browserhttp/pull/20 but closed it because my use case ended up being supported. I imagine I was originally down a path where I was using IHttpClientFactory as well - and then was able to wiggle back out of it. 

Feel free to take that, modify it, ignore it, etc.

**Comment by mtavares628** [comment]
So I've pulled down @benjaminsampica's pull request #20 and have tested it locally and it works with my code, as well as keeps the backwards compatibility with the HttpClient being created within the sink.

However, I just want to confirm that this code passes in the HttpClient, and not the IHttpClientFactory.  Even my quick and dirty test was using the IHttpClientFactory to create the HttpClient within program.cs and just passing that HttpClient to the extension method.  @nblumhardt were you looking to pass the IHttpClientFactory in instead?

If not, I would say that either Ben can re-submit his pull request, or I can pull it down and re-submit it from my fork.  Let me know what you guys would prefer.

**Comment by nblumhardt** [comment]
@mtavares628 I think `HttpClient` might be simpler than the factory - if we pass in the interface we'll also have to accept a name in order for the desired client to be returned. No strong opinions on this here though :-)

**Comment by mtavares628** [comment]
@nblumhardt just passing in the HttpClient works for me.  @benjaminsampica's code can be used as is then.  I will go ahead and re-submit his pull request.
