### ISSUE TITLE
Find a supported way to access `window.location.orgin`

### ISSUE THREAD

**Issue by nblumhardt** [nblumhardt/serilog-blazor#4]
We're currently using Blazor internals to get at this; at worst, we should fall back to the standard browser property.

https://github.com/nblumhardt/serilog-sinks-browserhttp/blob/bce82057aa356d940925a45dab471069b1628cac/src/Serilog.Sinks.BrowserHttp/Sinks/BrowserHttp/BrowserHttpSink.cs#L70

**Comment by pablopioli** [comment]
There is an additional drawback in the current implementation. If you log something before the host is instantiated, like show in the readme example (adapted)

            Log.Logger = new LoggerConfiguration()
                             .MinimumLevel.ControlledBy(levelSwitch)
                             .WriteTo.BrowserConsole()
                             .WriteTo.BrowserHttp("http://localhost:9777/ingest", controlLevelSwitch: levelSwitch)
                             .CreateLogger();

            Log.Error("Hello, browser!");

you get an error in the browser console

>   Uncaught (in promise) Error: System.Text.Json.JsonException: Invalid JSON
>   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS (Microsoft.JSInterop.JSRuntime jsRuntime, System.String arguments) <0x26d48a0 + 0x000fc> in <3eedf0ca90ca4e72bf6870618ca98c7c>:0 
>   at Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime.EndInvokeJS (System.String argsJson) <0x26d2610 + 0x0000a> in <d1b91dfced854ee99a396ef9a5cfcf72>:0 
>     at Object.callMethod (blazor.webassembly.js:1)
>     at Object.endInvokeJSFromDotNet (blazor.webassembly.js:1)
>     at blazor.webassembly.js:1
>

**Comment by nblumhardt** [comment]
Thanks @pablopioli - I've created a new issue based on your description.
